### ISSUE TITLE
Unable to connect with johnny-five / firmata.js

### ISSUE THREAD

**Issue by techniq** [adafruit/Adafruit_BLE_PinIO#10]
I've been having a lot of difficulty trying to get my new [Bluefruit LE UART Friend](https://www.adafruit.com/product/2479) to work with johnny-five/firmata.js.  I've followed the instructions outline [here](https://learn.adafruit.com/introducing-the-adafruit-bluefruit-le-uart-friend/configuration) and [here](https://learn.adafruit.com/bluefruit-le-connect-for-ios/library-and-config) to wire up and flash the special version of firmata to work with the module.

It appears to be able to connect using Node/johnny-five/firmata.js I need to use something like [ble-serial](https://github.com/monteslu/ble-serial) or [ble-serialport](https://github.com/elin-moco/ble-serialport) for the BLE virtualport, but thus far I've not had any success (it just hangs / times out).  I have left a similar issue on ble-serial's [issues](https://github.com/monteslu/ble-serial/issues/6), although I thought it was worth asking here.

I am able to connect to the device successfully using the Android [Bluefruit LE app](https://play.google.com/store/apps/details?id=com.adafruit.bluefruit.le.connect) and can control the onboard LED (pin 13) of my Arduino Nano using the app under Pin I/O.  I can also connect using the [Bluefruit LE Desktop app](https://github.com/adafruit/adafruit-bluefruit-le-desktop) (which uses javascript / noble library, but does not appear to use firmata / control I/O pins)

I've also seen a lot of discussion about merging the custom firmata for the nrf51822 in this repo into [StandardFirmataBLE](- https://github.com/firmata/arduino/tree/master/examples/StandardFirmataBLE), although it doesn't look like any progress has been made.

- https://github.com/adafruit/Adafruit_BLE_PinIO/issues/7
- https://github.com/adafruit/Adafruit_BLE_PinIO/pull/5
https://github.com/bbx10/Adafruit_BLEFirmata
https://github.com/bbx10/node-nRF8001

Any tips on how I can get this to work?  My end goal is to connect via React-Native, but first steps is being able to connect using firmata.js from my Mac.  Thanks.

**Comment by ladyada** [comment]
hiya, we did the firmata port for arduino but have never worked with j5. the uart friend is just a pass thru uart. if you can get j5 working with firmata then the uart friend can just go in between.

last we tried it, the custom firmata doesn't work very well on uno or 32u4, so we dont recommend using it 

only tips is lots of debugging, comparing uart traces between j5 and arduino, etc :)

**Comment by techniq** [comment]
@ladyada I think my confusion stems from what version of Firmata is needed to be flashed on the Nano (or any Arduino) to work with the UART Friend.  Is [BluefruitLE_nrf51822.ino](https://github.com/adafruit/Adafruit_BLE_PinIO/blob/master/examples/BluefruitLE_nrf51822/BluefruitLE_nrf51822.ino) not required?  Can StandardFirmata be used as long as TX1/RX0 are wired to the TX0/RX1 on the UART Friend?  I have no issues connecting to the Nano over USB order Bluetooth Classic using a JY-MCU adapter.

**Comment by ladyada** [comment]
BluefruitLE_nrf51822.ino is optimized but has only been tested in SPI mode. for plain UART mode, you can probably use regular Firmata since its 'transparent' - just make sure you're in data not command mode

**Comment by techniq** [comment]
If I leave the `MODE` pin not attached, and set the flip switch to UART, this should suffice, correct?

Thus far I haven't had any success trying this (with various Firmata versions).  I've also set the MODE pin to ground.

Based on this:

---
![screen shot 2016-11-25 at 1 34 29 am](https://cloud.githubusercontent.com/assets/177476/20616368/cfcf3b30-b2af-11e6-8504-e7cbc0c37181.png)

---

it seems like the MODE pin is required and thus the "custom firmata" be used.

Sorry for all the trouble.  I was really hoping switch from Bluetooth Classic to BLE was going to be fairly seamless, and choose the UART friend for this very reason:

---
![screen shot 2016-11-25 at 1 40 49 am](https://cloud.githubusercontent.com/assets/177476/20616437/59809d4c-b2b0-11e6-93ec-de0513ca1f20.png)

---

Should I have chosen the SPI version instead?

**Comment by techniq** [comment]
Based on the following data read, it appears I'm getting a response (0xf9 0x02 0x03) from the Arduino over BLE:

```
 ble-serial writing <Buffer f9> +4s
 ble-serial writing <Buffer f0 79 f7> +1ms
 ble-serial read <Buffer f9 02 03> true +86ms
```

Although I'm still not able to receive a "ready" event.  At this point I think i need to work with firmata.js / johnny-five to try and see if the issue resides there.

---

One thing worth pointing out before I close the issue, I seem to be having a lot of odd issues with the UART Friend initializing / factory resetting.  It seems 9 out of 10 times I have to close and reopen serial monitoring for the factory resetting of the UART Friend to succeed:

---
![screen shot 2016-11-25 at 2 15 54 am](https://cloud.githubusercontent.com/assets/177476/20617198/8683029e-b2b5-11e6-82de-e7314993baba.png)

---

![screen shot 2016-11-25 at 2 16 16 am](https://cloud.githubusercontent.com/assets/177476/20617200/89dd7ea6-b2b5-11e6-8599-871a74d5bac6.png)

**Comment by techniq** [comment]
@ladyada Thanks for your help earlier.  I wanted to report back I was able to successfully connect using fimata.js/johnny-five after changing the baudrate to 57600.  I didn't know this was possible based on the description on the production page (I thought it was hard set to 9600) but after changing to CMD mode and running `AT+BAUDRATE=57600` I am now in business (well, after also realizing I forgot to ground `CTS` since I was using hardware uart pins 0/1.

Thanks again.
