### ISSUE TITLE
Compatibility with Arduino Micro and Leonardo

### ISSUE THREAD

**Issue by dtwaddell** [adafruit/Adafruit_BLE_PinIO#2]
I see that Firmata has been updated to be compatible with Leonardo in version 2.3.2. Will the Adafruit BLE Firmata library be updated to reflect any of the changes? I tried updating my boards.h file with the micro specific pins and settings for the ATmega32u4, but the sketch still does not communicate with the iPhone app.  It appears to freeze while configuring all the pins (as seen from the serial monitor in Arduino).

**Comment by legozebra** [comment]
+1 same problem with Yún, which is Leonardo based.

**Comment by jaxzin** [comment]
Trying to use this with the Bluefruit Micro board and I think I'm hitting this issue.
```
In file included from C:\Users\Brian\Documents\Arduino\libraries\Adafruit_BLE_PinIO/Adafruit_BLE_Firmata.h:21:0,
                 from StandardFirmata.ino:34:
C:\Users\Brian\Documents\Arduino\libraries\Adafruit_BLE_PinIO/Boards.h:173:2: error: #error "Please edit Boards.h with a hardware abstraction for this board"
 #error "Please edit Boards.h with a hardware abstraction for this board"
  ^
```

**Comment by CollinCunningham** [comment]
We're currently working on adding support for the Bluefruit Micro - stay tuned!

**Comment by ladyada** [comment]
was done - BluefruitLE_nrf51822 supports Micro and Feather
