### ISSUE TITLE
Firmata_nRF8001 not working with Adafruit Bluefruit LE Connect v2.1.0

### ISSUE THREAD

**Issue by resolutedreamer** [adafruit/Adafruit_BLE_PinIO#9]
- Arduino board:  Arduino Uno

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.6.9

- Using LG Nexus 5 Android 6.0.1 
![screenshot_20160724-200239](https://cloud.githubusercontent.com/assets/3419924/17089360/e2e85192-51da-11e6-9d15-d2d839e40d61.png)

1. Open the Bluefruit LE app and click connect on the ADA_BLE device
2. Select Pin I/O
![screenshot_20160724-200529](https://cloud.githubusercontent.com/assets/3419924/17089373/0399af9e-51db-11e6-9bec-56fe628b0b91.png)
![screenshot_20160724-200255](https://cloud.githubusercontent.com/assets/3419924/17089375/0ce80870-51db-11e6-9e64-4142250961d7.png)
3. See Error Message
![screenshot_20160724-200543](https://cloud.githubusercontent.com/assets/3419924/17089378/16cd5340-51db-11e6-8616-d2b1e2c472e1.png)
On the Uno, this is what appears:
![ss3](https://cloud.githubusercontent.com/assets/3419924/17089389/385432ea-51db-11e6-9a5a-801ee8e052d4.PNG)

4. Note that PWM is not listed for pin 3 (or any of the pins)
![screenshot_20160724-200549](https://cloud.githubusercontent.com/assets/3419924/17089384/23300b50-51db-11e6-8bd1-566c4ffaa97e.png)

**Comment by resolutedreamer** [comment]
Using the commit from the repo described here:

https://github.com/adafruit/Adafruit_BLE_PinIO/issues/8,
https://github.com/adafruit/Adafruit_BLE_PinIO/tree/58a7b4dfbd5224d05192bd827200fcdcc597f1d8


the serial output of the Arduino Uno looks more interesting:

![ss1](https://cloud.githubusercontent.com/assets/3419924/17089405/69391128-51db-11e6-8de6-5618c9a11867.PNG)
![ss2](https://cloud.githubusercontent.com/assets/3419924/17089404/69389e5a-51db-11e6-9552-646587a406dc.PNG)

It looks like it is trying to connect but then it fails. With the newest version of the repo, it's unclear that the Uno even starts communicating with the app.

**Comment by microbuilder** [comment]
Fixed in https://github.com/adafruit/Bluefruit_LE_Connect_Android/commit/fc6100e96d2efecfa8e755c9fc462074d9cf8822 ... published to the Play Store as 2.1.1
